Initial HTML and JavaScript
lailagamaleldin/step pull request #1
Opened 2020-05-28 15:27 UTC by lailagamaleldin

Currently the HTML and JavaScript for the portfolio page have been built out. The index page's contents have been added although the contents of the resume and projects pages have yet to be added. 

All pages on the website come with a bar at the top that allows for navigation between the portfolio's different pages and to external sites like Linkedin and a UI portfolio built on Wix.

The home page contains a fun fun fact generator which is built using Javascript. A text file with facts is pre-loaded and the function responsible for returning the fun fact picks a random element from an array containing the contents of the text file.

2020-05-28 16:07 UTC, bsalazar19 requested changes

2020-05-28 16:07 UTC, bsalazar19 commented on portfolio/src/main/webapp/script.js
> +
nit: this spacing seems a bit weird. Please fix.

2020-05-28 18:39 UTC, wangding-google approved these changes

2020-05-29 18:10 UTC, bsalazar19 approved these changes

2020-06-01 14:21 UTC, merged